version: '3.8'

services:
    # notification-service:
    #     build: .
    #     image: notification-nestjs
    #     container_name: notification-service
    #     depends_on:
    #         - notification-service-db
    #     ports:
    #         - 5001:5000
    #     networks:
    #         - notificationservicenet

    notification-service-db:
        image: postgres
        container_name: notification-service-db
        restart: always
        environment:
            POSTGRES_DB: notification_service
            POSTGRES_USER: notificationservicedb
            POSTGRES_PASSWORD: notificationservicedb
        ports:
            - 5737:5432
        networks:
            - notificationservicenet

networks:
  notificationservicenet:
      driver: bridge
